# Generated by Django 2.0.1 on 2018-04-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examiner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=4, max_digits=7)),
                ('student', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_position', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('ict_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sid', models.CharField(max_length=5)),
                ('T_type', models.IntegerField(choices=[('0', 'Choice'), ('1', 'Short answer'), ('2', 'Interview and Practice')])),
                ('S_type', models.IntegerField(choices=[('0', 'One Instructor'), ('1', 'Multiple Instructor')])),
                ('Degree', models.IntegerField(choices=[('0', 'Bachelor'), ('1', 'Master'), ('2', 'Doctor')])),
                ('Examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Examiner')),
            ],
        ),
        migrations.AddField(
            model_name='examiner',
            name='name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='exam.Lac'),
        ),
    ]
