# Generated by Django 2.0.4 on 2018-04-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20180405_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='yeasr',
            field=models.CharField(default='25xx', max_length=4),
        ),
        migrations.AlterField(
            model_name='subject',
            name='Degree',
            field=models.CharField(choices=[('0', 'Bachelor'), ('1', 'Master'), ('2', 'Doctor')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='S_type',
            field=models.CharField(choices=[('0', 'One Instructor'), ('1', 'Multiple Instructor')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='T_type',
            field=models.CharField(choices=[('0', 'Choice'), ('1', 'Short answer'), ('2', 'Interview and Practice')], default='Choice', max_length=1),
        ),
    ]
