# Generated by Django 2.0.4 on 2018-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20180405_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['examiner']},
        ),
        migrations.AlterField(
            model_name='subject',
            name='T_type',
            field=models.CharField(choices=[('0', 'Choice'), ('1', 'Short answer'), ('2', 'Short answer and Choice'), ('3', 'Interview and Practice')], default='Choice', max_length=1),
        ),
    ]
