# Generated by Django 2.0.4 on 2018-04-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20180412_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='amount',
            field=models.IntegerField(default=1, max_length=2),
        ),
    ]
