# Generated by Django 2.0.4 on 2018-04-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_subject_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subject',
            name='ratio',
            field=models.FloatField(default='0.0000'),
        ),
    ]
