# Generated by Django 2.0.6 on 2018-08-31 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20180426_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='Section',
            field=models.CharField(default='foo', max_length=40),
        ),
    ]
