# Generated by Django 2.0.6 on 2018-08-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_subject_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='Section',
            field=models.CharField(choices=[('0', 'เคมี'), ('1', 'สิ่งทอ'), ('2', 'ฟิสิกส์'), ('3', 'เทคโนโลยีชนบท'), ('4', 'เทคโนโลยีชีวภาพ'), ('5', 'เทคโนโลยีการเกษตร'), ('6', 'คณิตศาสตร์และสถิติ'), ('7', 'วิทยาการคอมพิวเตอร์'), ('8', 'วิทยาศาสตร์สิ่งแวดล้อม'), ('9', 'วิทยาศาสตร์และเทคโนโลยีอาหาร')], default='0', max_length=1),
        ),
    ]
