# Generated by Django 2.0.6 on 2018-09-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20180831_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='ps',
            field=models.CharField(default='', max_length=100),
        ),
    ]
